services:
  pokemon-backend:
    container_name: pokemon-backend
    build:
      context: ./
      dockerfile: Dockerfile
    # image: api/app
    ports:
      - "3000:3000"
    # volumes:
    #   - .:/var/www/html
    # env_file:
    #   - ./.env
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    # command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - '5432:5432'
    container_name: postgresdb
    environment:
      POSTGRES_PASSWORD: supersecret
    volumes:
      - pgdata:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready"]
  #     interval: 1s
  #     timeout: 5s
  #     retries: 10
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
volumes:
  pgdata:
# volumes:
#   apimysql:
#     driver: local
