services:
  pokemon-backend:
    container_name: pokemon-backend
    build:
      context: ./
      dockerfile: Dockerfile
    # image: api/app
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: db
    depends_on:
      db:
        condition: service_started
      db-migration:
        condition: service_completed_successfully
  db-migration:
    container_name: db-migration
    build:
      context: ./
      dockerfile: Dockerfile.dbmigration
    environment:
      POSTGRES_HOST: db
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    container_name: postgresdb
    environment:
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: postgresql
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
